obj-y	+= mb_vma_lab/

obj-$(CONFIG_MB_LAB_PROCFS)	+= procfs_lab.o
obj-$(CONFIG_MB_LAB_COMPLETION)	+= completion_lab.o
obj-$(CONFIG_MB_LAB_WAITQUEUE)	+= waitqueue_lab.o
obj-$(CONFIG_MB_LAB_WORKQUEUE)	+= workqueue_lab.o
obj-$(CONFIG_MB_LAB_RADIX_TREE)	+= radix_tree_lab.o
obj-$(CONFIG_MB_LAB_RCU)	+= rcu_lab.o
